### ISSUE TITLE
Ordering of resources (eg components + component groups)

### ISSUE THREAD

**Issue by tonglil** [yannh/terraform-provider-statuspage#1]
Hey, thanks for putting the provider together!

In testing this provider, do you have any ideas for how TF can order the components?

Right now it seems to be ordered (without any modifications in SP) by newest to oldest.

Here is an idea:

1. Each resource, what your thoughts on using an arbitrarily weighted system? This should work for any top-level resources. For example:

```
resource "statuspage_component" "website" {
  page_id     = "${var.page_id}"
  name        = "My Website"
  description = "Status of my website"
  status      = ""
  weight      = -10  # (optional field, default = 0)
}

resource "statuspage_component" "below-website" {
  page_id     = "${var.page_id}"
  name        = "Below Website"
  description = "Status of my website"
  status      = ""
  weight      = -100  # (optional field, default = 0)
}

resource "statuspage_component" "above-website" {
  page_id     = "${var.page_id}"
  name        = "Above Website"
  description = "Status of my website"
  status      = ""
  weight      = 5  # (optional field, default = 0)
}

resource "statuspage_component" "above-group" {
  page_id     = "${var.page_id}"
  name        = "Above Group"
  description = "Status of my website"
  status      = ""
  weight      = 5  # (optional field, default = 0)
}

resource "statuspage_component_group" "my-group" {
  page_id     = "${var.page_id}"
  name        = "terraform"
  description = "Created by terraform"
  components = [
    "${statuspage_component.above-website.id}",
    "${statuspage_component.website.id}",
    "${statuspage_component.below-website.id}",
  ]
  weight      = 2  # (optional field, default = 0)
}
```

2a. For component ordering in a group, to use the ordering of the list in `statuspage_component_group.components[]`. This ignores `weight`s assigned to components, or..

2b. For components ordering in a group, to use the `weight`s assigned to components. This ignores the ordering of the list in `statuspage_component_group.components[]`.

I'm not familiar with the SP API so it might expect to do it differently?

**Comment by yannh** [comment]
Hi @tonglil ! The API returns a `"position": int` on component creation... and a ``"position": int` on component group creation? They are not listed as parameters that can be set, but let's see what happens!

**Comment by yannh** [comment]
It doesn't look like Statuspage API's  components endpoint accepts the "position" parameter (it returns 403 if position is set). This parameter would need to be added to be implemented here. However - you should be able to sort your components created by Terraform in Statuspage' UI - the terraform plans should stay empty.
