### ISSUE TITLE
Datadog Provider not working

### ISSUE THREAD

**Issue by ncrothe** [yannh/terraform-provider-statuspage#3]
We are trying to integrate Datadog metrics via the terraform provider.

We are using
```
resource "statuspage_metrics_provider" "datadog" {
  page_id   = "MY_PAGE_ID"
  api_key   = "MY_API_KEY"
  api_token = "MY_APPLICATION_KEY"
  type      = "Datadog"
}
```

but that yields an error
```
* statuspage_metrics_provider.datadog: failed creating metrics_provider, request returned 422, full
response: &{Status:422 Unprocessable Entity StatusCode:422 Proto:HTTP/2.0 ProtoMajor:2 ProtoMinor:0
Header:map[Cache-Control:[no-cache] Content-Length:[44] Content-Type:[application/json] Vary:[Origin]
X-Request-Id:[19417729-28a1-4432-a646-3004e69bee25] X-Runtime:[0.075292]] Body:{cs:0xc0005e2dc0}
ContentLength:44 TransferEncoding:[] Close:false Uncompressed:false Trailer:map[]
Request:0xc000122500 TLS:0xc0004308f0}
```

Reading through your code and the API docs, I assume the error is that the provider uses (and checks for) APIKey and APIToken whereas the API expects api_key and application_key.

**Comment by yannh** [comment]
Hi @ncrothe , yeah the Datadog provider was really best effort since I did not have an account to test! Thanks for the report, I will investigate!

**Comment by ncrothe** [comment]
Thanks, much appreciated. Tried tinkering with it myself, but didn't get far - ran into marshalling issues.

**Comment by yannh** [comment]
Hi ncrothe, I think I fixed it... Statuspage's documentation states that you need to use api_key and api_token ( https://developer.statuspage.io/#operation/postPagesPageIdMetricsProviders ) but it looks like that's not correct and that you need to set api_key and application_key instead... I have updated the sdk and the terraform provider, and have been able to successfully setup the integration. 
Since I have now a datadog account I might write acceptance tests for this :) Please confirm this works for you!

**Comment by ncrothe** [comment]
I can confirm that I can manage the metrics_provider now. Unfortunately, I was not able to set up metrics. TF is reporting an EOF error:
```
terraform apply ./prepared.plan
statuspage_metric.dd_api_requests: Creating...
  metric_identifier:   "" => "sum:apache.net.request_per_s{project:forum}"
  metrics_provider_id: "" => "vk9rcp9m6cs6"
  name:                "" => "Forum2"
  page_id:             "" => "5t65x38g8t68"

Error: Error applying plan:

1 error(s) occurred:

* statuspage_metric.dd_api_requests: 1 error(s) occurred:

* statuspage_metric.dd_api_requests: unexpected EOF

```

That is based on a resource definition like
```
resource "statuspage_metric" "forum_requests" {
  page_id             = "MYPAGEID"
  metrics_provider_id = "${statuspage_metrics_provider.datadog.id}"
  name                = "Forum"
  metric_identifier   = "sum:apache.net.request_per_s{project:forum}"
}
```
It does work in the UI. I captured the form post and it looks very similar:
```
metrics_display_id: 
metric[metrics_provider_id]: vk9rcp9m6cs6
metric[type]: DatadogMetric
metric[metric_identifier]: sum:apache.net.request_per_s{project:forum}
metric[name]: Forum requests
metrics_display[suffix]: reqs/min
```
Not sure where the EOF might be coming from.

**Comment by yannh** [comment]
Thanks for the feedback! I ll add more tests.

**Comment by ncrothe** [comment]
Statuspage support got back to me after I broke my admin page playing around with the provider and said 

> The issue is that the type needs to be 'DataDogMetricsProvider' not 'DataDog'.

Which I assume refers to the type parameter in the create (or in my case update) metric provider call.

**Comment by yannh** [comment]
Thanks for following up! I'll fix this in the coming days. This is not reflected in the API doc which says "Datadog" either though.. I might start maintaining a small file about issues in the API doc, for future reference.

**Comment by ncrothe** [comment]
FWIW, they realized the same:
> Thanks for let me know. We have also opened an additional ticket to get the documentation corrected as I think it actually states to use datadog only which is incorrect.

**Comment by generalhenry** [comment]
The valid types are: PingdomMetricsProvider, NewRelicMetricsProvider, LibratoMetricsProvider, DatadogMetricsProvider, SelfMetricsProvider

I've raised an issue to fix our docs.

**Comment by yannh** [comment]
Hi @generalhenry ! Thanks for popping by :) Just to clarify: are these the right values for the "type" parameter when creating a metric provider? I don't seem to get that to work, when Datadog does work to create the metric provider :thinking: @ncrothe seems to mention that he had issues when creating a metric, the data he shows seem to show a Type: DatadogMetric which I cant find in the documentation. Any insights or updates to the doc much appreciated :+1:

**Comment by yannh** [comment]
@ncrothe I ve found issues in the metric creation code in my SDK - I ve also added a test around metric creation. The API for creating metrics is a little bit different from other resources - it expects a POST on /pages/{page_id}/metrics_providers/{metrics_provider_id}/metrics , when the SDK would have expected /pages/{page_id}/metrics . 

The following now works:


`provider "statuspage" {
  token = "token"
}

resource "statuspage_metrics_provider" "datadog1" {
    page_id = "xxxx"
    api_key = ""
    application_key = ""
    type = "Datadog"
}

resource "statuspage_metric" "datadog_metric" {
		page_id             = "xxxx"
		metrics_provider_id = "${statuspage_metrics_provider.datadog1.id}"
		name                = "Forum"
		metric_identifier   = "sum:apache.net.request_per_s{project:forum}"
	}`

**Comment by yannh** [comment]
Closing, as this should be fixed!
