### ISSUE TITLE
support incident templates creation and management

### ISSUE THREAD

**Issue by patelronak** [yannh/terraform-provider-statuspage#30]
Can you please support the creation and management of incident templates?

https://developer.statuspage.io/#operation/postPagesPageIdIncidentTemplates

**Comment by yannh** [comment]
Good question... is this endpoint really missing a delete? :thinking:

**Comment by yannh** [comment]
@patelronak I am going to close this - the Statuspage API does not have full CRUD support for incident templates - there is only an endpoint to create a template. There is no documented way to update or delete a template. If the docs were updated to include those, I would add support.
See https://developer.statuspage.io/#operation/getPagesPageIdIncidentTemplates
