### ISSUE TITLE
Updating page_id for a component doesn't work

### ISSUE THREAD

**Issue by krivachy** [yannh/terraform-provider-statuspage#31]
If I just change the page_id then the plan will be:

```
  # module.statuspage_component["test_component"].statuspage_component.test_component will be updated in-place
  ~ resource "statuspage_component" "test_component" {
        automation_email      = "component+XXXXX@notifications.statuspage.io"
        description           = "Test component"
        id                    = "3aatyllodd78"
        name                  = "test_component"
        only_show_if_degraded = false
      ~ page_id               = "1dm8qkaypshw" -> "eweq026a3hrd"
        showcase              = true
        status                = "operational"
    }
```

I get a an error message when applying this plan:

```
Error: failed updating component, request returned 404
```

This seems to be, because the [`PUT 
/pages/{page_id}/components/{component_id}` API](https://developer.statuspage.io/#operation/putPagesPageIdComponentsComponentId) has the page id in its path parameter.

The fix seems to be to have the plan destroy the previous component on the old page and create a new component on the new page.

**Comment by yannh** [comment]
Hi @krivachy , thanks  a lot for the bug report! Happy to merge Pull Requests - otherwise I can fix this myself but I can't promise an ETA :)

**Comment by yannh** [comment]
WIP https://github.com/yannh/terraform-provider-statuspage/pull/35  - not tested at all yet, I will need to add an acceptance test. However if that approach works, it would not be too bad :)

**Comment by yannh** [comment]
Fixed by #35

**Comment by krivachy** [comment]
Thanks @yannh a bunch! It's much appreciated 😊

**Comment by yannh** [comment]
Just released a new version with the fix :bow:  Thx again for the bug report :)
