### ISSUE TITLE
terraform error after manually deleting a component from statuspage

### ISSUE THREAD

**Issue by ghost** [yannh/terraform-provider-statuspage#36]
Hello,
This provider does not seem to appreciate when a component is (manually) deleted from statuspage.
After manual deletion, I got:
```
terraform plan
[...]
Error: could not find component with ID: 9nt3wb5yrbm9, http status 404
```
I expected for terraform plan to succeed and propose to reprovision the component.

```
Terraform v0.13.6
+ provider registry.terraform.io/yannh/statuspage v0.1.7
```

**Comment by yannh** [comment]
Urgh, so would I, thanks for the report :heart:

**Comment by yannh** [comment]
I tried a fix for this - but I have not been able to really write a test for this yet, so I am unsure if this is actually fixed. Writing a test for this is a bit of a challenge, hopefully I'll get back to it soon :+1:

**Comment by mtaylor-evidation** [comment]
Any updates on this I'm experiencing this issue also.

**Comment by yannh** [comment]
Fixed in v0.1.12 :bow: It should include such a note now : 
![image](https://user-images.githubusercontent.com/210669/167781440-f08bea34-d7cf-4d4b-8409-c4b5d75be3ac.png)

**Comment by yannh** [comment]
Mh reopening since the CI is failing for some reason, though that seems unrelated to this change :thinking:

**Comment by yannh** [comment]
Fixed and repushed the tag , was linked to https://github.com/hashicorp/hc-install/issues/59  - it's really quite bad that they did not manage to make this change backward compatible, all providers might fail to build now, and it will be potentially impossible to rebuild older versions of any providers without change.
