### ISSUE TITLE
Ordering of component groups

### ISSUE THREAD

**Issue by ncrothe** [yannh/terraform-provider-statuspage#4]
Hi,

I have created a statuspage with multiple components and a component group that inclused these component. However, with the current implementation the provider seems to use a different ordering than what is returned  by the API. The result is that on every TF run it tries to reorder the components.

Example:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ statuspage_component_group.web
      components.0: "f30f5bxdjkm3" => "n7r1jhzvlndy"
      components.1: "g79sjl6272y6" => "q4nxjxgwb0pc"
      components.2: "q4nxjxgwb0pc" => "f30f5bxdjkm3"
      components.3: "n7r1jhzvlndy" => "g79sjl6272y6"


Plan: 0 to add, 1 to change, 0 to destroy.
```
Executing that plan and running `terraform plan` again results in the same plan.

This makes it hard to detect drift.

Expected behaviour: After setting up a component group with some ordering, the next run will show no changes.

**Comment by yannh** [comment]
Thank you for the bug report. I will look into this.

**Comment by yannh** [comment]
I tried sorting the slice when reading/writing, but it doesnt seem to help. I ll have another go another day.

**Comment by ncrothe** [comment]
Haven't looked into the details of this, but noticed many other providers use hashes instead of indexes for list-type values.

**Comment by yannh** [comment]
I have done what is suggested here: https://github.com/hashicorp/terraform/issues/16297  - now using TypeSet instead of TypeList, TypeSet being for unordered lists, seems more appropriate here. Tests seem to be consistently passing, this should be solved.

**Comment by yannh** [comment]
Closing, this should be solved.
