### ISSUE TITLE
Support for Apple Silicon

### ISSUE THREAD

**Issue by 0x46616c6b** [yannh/terraform-provider-statuspage#40]
Would it be possible to support Apple Silicon (darwin_arm64) for the Provider? This would be awesome!

**Comment by yannh** [comment]
Published v0.1.9 - updated goreleaser. Took a few iterations to get right (had to recreate my statuspage account since they deleted it, and I need to setup GPG in Github), please let me know if this works for you :pray:  Thanks!

**Comment by yannh** [comment]
Yes it looks like it's missing, damn :( https://github.com/yannh/terraform-provider-statuspage/releases  I spent some time fixing the release workflow to be automated, and had to revert to use the GH action. I might look at it this evening, or wait for https://github.com/goreleaser/goreleaser/pull/2905 to be in the next goreleaser release, this is what blocked me yesterday :)

Can you pin to 0.1.9 in the meantime? I'll reopen this.

**Comment by 0x46616c6b** [comment]
Yeah, I can of course use the `0.1.9`. Thanks for looking again in this issue.

**Comment by caiconkhicon** [comment]
Can you please push 0.1.10 :D I am waiting for it

**Comment by yannh** [comment]
I ve updated goreleaser, this should be fixed!
