### ISSUE TITLE
Support for setting a start date

### ISSUE THREAD

**Issue by lukeamaral** [yannh/terraform-provider-statuspage#51]
It doesn't seem like there is any support for setting the `start_date` field.

The API does support it, so I believe this should be trivial.

**Comment by yannh** [comment]
Should be solved by https://github.com/yannh/terraform-provider-statuspage/pull/56 ! Sorry for the mess with the pull request & reverts :/ Should I try to add you as co-author on the commits? Thank you so much for figuring this out :100: :medal_sports:  :heart:

**Comment by lukeamaral** [comment]
No worries. I'm glad it worked now. If it's trivial to add as co-author it would be nice, but don't need to worry about it, my original commits are still in the commit history.
